[env]
https_proxy="http://127.0.0.1:7897"
http_proxy="http://127.0.0.1:7897"
all_proxy="socks5://127.0.0.1:7897"

[window]
padding = { x = 10, y = 10 }
dynamic_padding = true
opacity = 0.80
blur = true

[font]
size = 14
